version: '3.7'

services:
    client:
      build: ./client/
      volumes:
        - "./client:/app"
      ports:
        - "4200:4200"
      depends_on:
        - api

    api:
      build: ./api/
      volumes:
        - "./api:/app"
      ports:
        - "3000:3000"
